using BooksApp.Entity.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;

namespace BooksApp.Data.Concrete.EfCore.Config
{
    public class BookConfig : IEntityTypeConfiguration<Book>
    {
        public void Configure(EntityTypeBuilder<Book> builder)
        {
            builder.Property(x => x.Id).ValueGeneratedOnAdd();

            builder.Property(x => x.CreatedDate).IsRequired();
            builder.Property(x => x.ModifiedDate).IsRequired();

            builder.Property(x => x.Name).IsRequired().HasMaxLength(100);

            builder.Property(x => x.Stock).IsRequired();

            builder.Property(x => x.Price).IsRequired();

            builder.Property(x => x.PageCount).IsRequired();

            builder.Property(x => x.EditionYear).IsRequired();

            builder.Property(x => x.EditionNumber).IsRequired();

            builder.HasData(
                new Book { Id = 1, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Fahrenheit 451", Stock = 10, Price = 75, PageCount = 150, EditionYear = 2020, EditionNumber = 1, Url="fahrenheit-451", Summary= "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 2, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Kadınlar Ülkesи", Stock = 10, Price = 175, PageCount = 120, EditionYear = 2010, EditionNumber = 43, Url="kadinlar-ulkesi", Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 3, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Инсанлар", Stock = 10, Price = 705, PageCount = 180, EditionYear = 2010, EditionNumber = 13, Url="insanlar" , Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 4, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Невидимый Человек", Stock = 10, Price = 15, PageCount = 190, EditionYear = 2022, EditionNumber = 2, Url="nevli-cesur" , Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 5, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Черный Дневник", Stock = 10, Price = 47, PageCount = 250, EditionYear = 2018, EditionNumber = 13, Url="siyah-gunce" , Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 6, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Книга Голубого Неба", Stock = 10, Price = 68, PageCount = 50, EditionYear = 2016, EditionNumber = 8, Url="nebonun-mavi-kitabi" , Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 7, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Ресторан в Конце Вселенной", Stock = 0, Price = 114, PageCount = 15, EditionYear = 2021, EditionNumber = 7, Url="evrenin-sonundaki-restoran", Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 8, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Кто меня убил?", Stock = 10, Price = 247, PageCount = 330, EditionYear = 2020, EditionNumber = 4, Url="beni-kim-oldurdu" , Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 9, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Библиотека Ума", Stock = 0, Price = 300, PageCount = 240, EditionYear = 2022, EditionNumber = 1, Url="zihin-kutuphanesi" , Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 10, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Новая Жизнь", Stock = 10, Price = 166, PageCount = 400, EditionYear = 2019, EditionNumber = 11, Url="yeni-bir-yasam" , Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 11, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Королева Ночи", Stock = 10, Price = 19, PageCount = 97, EditionYear = 2020, EditionNumber = 12, Url="gecenin-kralicesi" , Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." },
                new Book { Id = 12, CreatedDate = DateTime.Now, ModifiedDate = DateTime.Now, IsApproved = true, Name = "Секретный Сад", Stock = 10, Price = 19, PageCount = 97, EditionYear = 2020, EditionNumber = 12, Url="gizli-bahce" , Summary = "Насколько далеко...\r\nНесмотря на общее мнение, Lorem Ipsum не является просто случайным набором букв. Он имеет корни в классической латыни с более чем двухтысячелетней историей. Профессор латыни из колледжа Гампдена-Сиднея в штате Вирджиния Ричард МакКлинток, исследовав один из Lorem Ipsum пассажей, исследовав в течение долгого времени литературные произведения на латыни, обнаружил неоспоримый источник. Lorem Ipsum происходит из разделов 1.10.32 и 1.10.33 книги \"de Finibus Bonorum et Malorum\" (О пределах добра и зла) Цицерона, написанной в 45 году до н.э. Эта книга является трактатом по теории этики и была очень популярна в эпоху Возрождения. Первая строка Lorem Ipsum, \"Lorem ipsum dolor sit amet\", взята из строки в разделе 1.10.32." }
            );
        }
    }
}
